# https://docs.python.org/3/howto/unicode.html
# Be sure to add U+ before the code
# 0061 - LATIN SMALL LETTER A
# 0062 - LATIN SMALL LETTER B
# 0063 - LATIN SMALL LETTER B

# 007B LEFT CURLY BRACKET

# 2167 ROMAN NUMERAL EIGHT
# 2168 ROMAN NUMERAL NINE

#265E BLACK CHESS KNIGHT
#265F BLACK CHESS PAWN

# THESE ARE JUST SOME EXAMPLES